### ISSUE TITLE
有时候正常运行过程中会报这个错

### ISSUE THREAD

**Issue by zhoulinxiang** [koajs/ejs#42]
RangeError: Maximum call stack size exceeded
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:85:26)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)
at ejs.resolveInclude (/aaa/node_modules/koa-ejs/index.js:89:14)

然后后面的渲染就全挂了，一直报这个错

**Comment by Runrioter** [comment]
@zhoulinxiang  这个已经修复了  等待 @dead-horse  发布新的版本

**Comment by Runrioter** [comment]
@ViGo5190  Now it is updated, please update it
