### ISSUE TITLE
when cache is true, something wrong will be

### ISSUE THREAD

**Issue by fangxu864** [koajs/ejs#69]
line79     if (settings.cache && cache[viewPath]) return cache[viewPath](options.scope, options)

should be

return cache[viewPath].call()

**Comment by hckhanh** [comment]
The same with me, the cache is not found. Can you check on that, @titanism?

**Comment by titanism** [comment]
Please provide a working example or a test that demonstrates this is a bug.

**Comment by jalfonso** [comment]
This occurs for me with `@koa/ejs@5.0.0` when using cache + layout.   

Using the [example code](https://github.com/koajs/ejs/blob/master/README.md#example) with `cache: true` and a simple layout template:

```html
<%- body %>
```

The first render is successful but subsequent calls throw:

```
  ReferenceError: body is not defined
      at eval (eval at compile (/tmp/koa-ejs-cache-issue/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:6:17)
      at Object.template [as /tmp/koa-ejs-cache-issue/view/template.html] (/tmp/koa-ejs-cache-issue/node_modules/ejs/lib/ejs.js:703:17)
      at render (/tmp/koa-ejs-cache-issue/node_modules/@koa/ejs/index.js:79:66)
      at app.context.render (/tmp/koa-ejs-cache-issue/node_modules/@koa/ejs/index.js:108:20)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /tmp/koa-ejs-cache-issue/index.js:15:3
```

**Comment by kissycn** [comment]
I have encountered the same problem
